/* Static extension loader for Jim Tcl on ESP32
 *
 * Replaces the autogenerated load-static-exts.c from the normal build.
 * Registers all statically compiled extensions in the correct order.
 */

#include "jim.h"
#include "jim-esp32.h"

/* Standard Jim extensions compiled in */
extern int Jim_packageInit(Jim_Interp *interp);
extern int Jim_namespaceInit(Jim_Interp *interp);
extern int Jim_interpInit(Jim_Interp *interp);
extern int Jim_arrayInit(Jim_Interp *interp);
extern int Jim_clockInit(Jim_Interp *interp);
extern int Jim_tclprefixInit(Jim_Interp *interp);

int Jim_InitStaticExtensions(Jim_Interp *interp)
{
    /* Core Jim extensions (order matters: stdlib-like first) */
    Jim_packageInit(interp);
    Jim_namespaceInit(interp);
    Jim_arrayInit(interp);
    Jim_clockInit(interp);
    Jim_tclprefixInit(interp);
    Jim_interpInit(interp);

    /* ESP32-specific extensions */
    Jim_gpioInit(interp);
    Jim_wifiInit(interp);
    Jim_i2cInit(interp);
    Jim_nvsInit(interp);
    Jim_esp_taskInit(interp);
    Jim_ieee802154Init(interp);

    return JIM_OK;
}
