/* Static extension loader for Jim Tcl on ESP32
 *
 * Replaces the autogenerated load-static-exts.c from the normal build.
 * Registers all statically compiled extensions in the correct order.
 */

#include "jim.h"
#include "jim-esp32.h"
#include "soc/soc_caps.h"

/* Standard Jim extensions compiled in */
extern int Jim_packageInit(Jim_Interp *interp);
extern int Jim_namespaceInit(Jim_Interp *interp);
extern int Jim_interpInit(Jim_Interp *interp);
extern int Jim_arrayInit(Jim_Interp *interp);
extern int Jim_clockInit(Jim_Interp *interp);
extern int Jim_tclprefixInit(Jim_Interp *interp);

int Jim_InitStaticExtensions(Jim_Interp *interp)
{
    /* Core Jim extensions (order matters: stdlib-like first) */
    Jim_packageInit(interp);
    Jim_namespaceInit(interp);
    Jim_arrayInit(interp);
    Jim_clockInit(interp);
    Jim_tclprefixInit(interp);
    Jim_interpInit(interp);

    /* ESP32-specific extensions */
    Jim_gpioInit(interp);
    Jim_wifiInit(interp);
    Jim_i2cInit(interp);
    Jim_nvsInit(interp);
    Jim_esp_taskInit(interp);
#if defined(SOC_IEEE802154_SUPPORTED) && SOC_IEEE802154_SUPPORTED
    Jim_ieee802154Init(interp);
#endif
    Jim_sleepInit(interp);
    Jim_watchdogInit(interp);

    /* Protocol extensions (Kconfig-gated) */
#ifdef CONFIG_JIM_EXT_HTTP
    Jim_httpInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_MQTT
    Jim_mqttInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_WEBSOCKET
    Jim_websocketInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_JSON
    Jim_jsonInit(interp);
#endif
#if defined(CONFIG_JIM_EXT_TWAI) && defined(SOC_TWAI_SUPPORTED)
    Jim_twaiInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_SERIAL
    Jim_serialInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_ADC
    Jim_adcInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_PWM
    Jim_pwmInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_TIMER
    Jim_timerInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_FS
    Jim_fsInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_OTA
    Jim_otaInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_SPI
    Jim_spiInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_ONEWIRE
    Jim_onewireInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_CRON
    Jim_cronInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_SYSLOG
    Jim_syslogInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_TEST
    Jim_testInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_TCP
    Jim_tcpInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_BLE
    Jim_bleInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_ESPNOW
    Jim_espnowInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_MDNS
    Jim_mdnsInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_SNTP
    Jim_sntpInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_MODBUS
    Jim_modbusInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_MPACK
    Jim_mpackInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_CTLPLANE
    Jim_ctlplaneInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_RMT
    Jim_rmtInit(interp);
#endif
#ifdef CONFIG_JIM_EXT_PCNT
    Jim_pcntInit(interp);
#endif
#if defined(CONFIG_JIM_EXT_MCPWM) && defined(SOC_MCPWM_SUPPORTED)
    Jim_mcpwmInit(interp);
#endif

    return JIM_OK;
}
